import { PrismaClient, MuscleGroup, Equipment, MovementPattern, Difficulty } from "@prisma/client";

const prisma = new PrismaClient();

type ExerciseSeed = {
  name: string;
  primaryMuscle: MuscleGroup;
  secondaryMuscles: MuscleGroup[];
  equipment: Equipment;
  movementPattern: MovementPattern;
  difficulty: Difficulty;
  isCompound: boolean;
  exerciseFamily: string;
  isCustom: false;
};

const exercises: ExerciseSeed[] = [
  // ── CHEST ─────────────────────────────────────────────────────────────────
  {
    name: "Bench Press",
    primaryMuscle: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    equipment: Equipment.BARBELL,
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    difficulty: Difficulty.INTERMEDIATE,
    isCompound: true,
    exerciseFamily: "bench_press",
    isCustom: false,
  },
  {
    name: "Incline Bench Press",
    primaryMuscle: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    equipment: Equipment.BARBELL,
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    difficulty: Difficulty.INTERMEDIATE,
    isCompound: true,
    exerciseFamily: "bench_press",
    isCustom: false,
  },
  {
    name: "Decline Bench Press",
    primaryMuscle: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    equipment: Equipment.BARBELL,
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    difficulty: Difficulty.INTERMEDIATE,
    isCompound: true,
    exerciseFamily: "bench_press",
    isCustom: false,
  },
  {
    name: "Smith Machine Bench Press",
    primaryMuscle: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    equipment: Equipment.SMITH_MACHINE,
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    difficulty: Difficulty.BEGINNER,
    isCompound: true,
    exerciseFamily: "bench_press",
    isCustom: false,
  },
  {
    name: "Dumbbell Bench Press",
    primaryMuscle: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    equipment: Equipment.DUMBBELL,
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    difficulty: Difficulty.BEGINNER,
    isCompound: true,
    exerciseFamily: "bench_press",
    isCustom: false,
  },
  {
    name: "Incline Dumbbell Press",
    primaryMuscle: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    equipment: Equipment.DUMBBELL,
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    difficulty: Difficulty.BEGINNER,
    isCompound: true,
    exerciseFamily: "bench_press",
    isCustom: false,
  },
  {
    name: "Chest Press Machine",
    primaryMuscle: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    equipment: Equipment.MACHINE,
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    difficulty: Difficulty.BEGINNER,
    isCompound: true,
    exerciseFamily: "bench_press",
    isCustom: false,
  },
  {
    name: "Push-Up",
    primaryMuscle: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS, MuscleGroup.CORE],
    equipment: Equipment.BODYWEIGHT,
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    difficulty: Difficulty.BEGINNER,
    isCompound: true,
    exerciseFamily: "bench_press",
    isCustom: false,
  },
  {
    name: "Dips",
    primaryMuscle: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    equipment: Equipment.BODYWEIGHT,
    movementPattern: MovementPattern.VERTICAL_PUSH,
    difficulty: Difficulty.INTERMEDIATE,
    isCompound: true,
    exerciseFamily: "dip",
    isCustom: false,
  },
  {
    name: "Assisted Dip Machine",
    primaryMuscle: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    equipment: Equipment.MACHINE,
    movementPattern: MovementPattern.VERTICAL_PUSH,
    difficulty: Difficulty.BEGINNER,
    isCompound: true,
    exerciseFamily: "dip",
    isCustom: false,
  },
  {
    name: "Cable Fly",
    primaryMuscle: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    equipment: Equipment.CABLE,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "fly",
    isCustom: false,
  },
  {
    name: "Incline Cable Fly",
    primaryMuscle: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    equipment: Equipment.CABLE,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "fly",
    isCustom: false,
  },
  {
    name: "Pec Deck",
    primaryMuscle: MuscleGroup.CHEST,
    secondaryMuscles: [],
    equipment: Equipment.MACHINE,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "fly",
    isCustom: false,
  },
  {
    name: "Converging Chest Press",
    primaryMuscle: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    equipment: Equipment.MACHINE,
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    difficulty: Difficulty.BEGINNER,
    isCompound: true,
    exerciseFamily: "bench_press",
    isCustom: false,
  },
  {
    name: "Reverse Pec Deck",
    primaryMuscle: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.TRAPS, MuscleGroup.BACK],
    equipment: Equipment.MACHINE,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "lateral_raise",
    isCustom: false,
  },

  // ── BACK ──────────────────────────────────────────────────────────────────
  {
    name: "Pull-Up",
    primaryMuscle: MuscleGroup.LATS,
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.BACK, MuscleGroup.CORE],
    equipment: Equipment.BODYWEIGHT,
    movementPattern: MovementPattern.VERTICAL_PULL,
    difficulty: Difficulty.INTERMEDIATE,
    isCompound: true,
    exerciseFamily: "pull_up",
    isCustom: false,
  },
  {
    name: "Lat Pulldown",
    primaryMuscle: MuscleGroup.LATS,
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.BACK],
    equipment: Equipment.CABLE,
    movementPattern: MovementPattern.VERTICAL_PULL,
    difficulty: Difficulty.BEGINNER,
    isCompound: true,
    exerciseFamily: "lat_pulldown",
    isCustom: false,
  },
  {
    name: "Close Grip Lat Pulldown",
    primaryMuscle: MuscleGroup.LATS,
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.BACK],
    equipment: Equipment.CABLE,
    movementPattern: MovementPattern.VERTICAL_PULL,
    difficulty: Difficulty.BEGINNER,
    isCompound: true,
    exerciseFamily: "lat_pulldown",
    isCustom: false,
  },
  {
    name: "Straight Arm Pulldown",
    primaryMuscle: MuscleGroup.LATS,
    secondaryMuscles: [MuscleGroup.CORE],
    equipment: Equipment.CABLE,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "lat_pulldown",
    isCustom: false,
  },
  {
    name: "Barbell Row",
    primaryMuscle: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.LATS, MuscleGroup.BICEPS, MuscleGroup.TRAPS],
    equipment: Equipment.BARBELL,
    movementPattern: MovementPattern.HORIZONTAL_PULL,
    difficulty: Difficulty.INTERMEDIATE,
    isCompound: true,
    exerciseFamily: "row",
    isCustom: false,
  },
  {
    name: "Dumbbell Row",
    primaryMuscle: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.LATS, MuscleGroup.BICEPS],
    equipment: Equipment.DUMBBELL,
    movementPattern: MovementPattern.HORIZONTAL_PULL,
    difficulty: Difficulty.BEGINNER,
    isCompound: true,
    exerciseFamily: "row",
    isCustom: false,
  },
  {
    name: "Seated Cable Row",
    primaryMuscle: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.LATS, MuscleGroup.BICEPS, MuscleGroup.TRAPS],
    equipment: Equipment.CABLE,
    movementPattern: MovementPattern.HORIZONTAL_PULL,
    difficulty: Difficulty.BEGINNER,
    isCompound: true,
    exerciseFamily: "row",
    isCustom: false,
  },
  {
    name: "T-Bar Row",
    primaryMuscle: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.LATS, MuscleGroup.BICEPS, MuscleGroup.TRAPS],
    equipment: Equipment.BARBELL,
    movementPattern: MovementPattern.HORIZONTAL_PULL,
    difficulty: Difficulty.INTERMEDIATE,
    isCompound: true,
    exerciseFamily: "row",
    isCustom: false,
  },
  {
    name: "Chest Supported Row",
    primaryMuscle: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.LATS, MuscleGroup.BICEPS, MuscleGroup.TRAPS],
    equipment: Equipment.DUMBBELL,
    movementPattern: MovementPattern.HORIZONTAL_PULL,
    difficulty: Difficulty.BEGINNER,
    isCompound: true,
    exerciseFamily: "row",
    isCustom: false,
  },
  {
    name: "Face Pull",
    primaryMuscle: MuscleGroup.TRAPS,
    secondaryMuscles: [MuscleGroup.SHOULDERS, MuscleGroup.BACK],
    equipment: Equipment.CABLE,
    movementPattern: MovementPattern.HORIZONTAL_PULL,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "row",
    isCustom: false,
  },
  {
    name: "Plate-Loaded Lat Pulldown",
    primaryMuscle: MuscleGroup.LATS,
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.BACK],
    equipment: Equipment.MACHINE,
    movementPattern: MovementPattern.VERTICAL_PULL,
    difficulty: Difficulty.BEGINNER,
    isCompound: true,
    exerciseFamily: "lat_pulldown",
    isCustom: false,
  },
  {
    name: "Archer Pull",
    primaryMuscle: MuscleGroup.LATS,
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.BACK, MuscleGroup.CORE],
    equipment: Equipment.BODYWEIGHT,
    movementPattern: MovementPattern.VERTICAL_PULL,
    difficulty: Difficulty.ADVANCED,
    isCompound: true,
    exerciseFamily: "pull_up",
    isCustom: false,
  },
  {
    name: "Single Arm Row",
    primaryMuscle: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.LATS, MuscleGroup.BICEPS],
    equipment: Equipment.CABLE,
    movementPattern: MovementPattern.HORIZONTAL_PULL,
    difficulty: Difficulty.BEGINNER,
    isCompound: true,
    exerciseFamily: "row",
    isCustom: false,
  },
  {
    name: "Cable Lat Pullover",
    primaryMuscle: MuscleGroup.LATS,
    secondaryMuscles: [MuscleGroup.CHEST, MuscleGroup.CORE],
    equipment: Equipment.CABLE,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "lat_pulldown",
    isCustom: false,
  },
  {
    name: "Dumbbell Lat Pullover",
    primaryMuscle: MuscleGroup.LATS,
    secondaryMuscles: [MuscleGroup.CHEST, MuscleGroup.TRICEPS],
    equipment: Equipment.DUMBBELL,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "lat_pulldown",
    isCustom: false,
  },
  {
    name: "Deadlift",
    primaryMuscle: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.TRAPS, MuscleGroup.QUADS],
    equipment: Equipment.BARBELL,
    movementPattern: MovementPattern.HINGE,
    difficulty: Difficulty.ADVANCED,
    isCompound: true,
    exerciseFamily: "hip_hinge",
    isCustom: false,
  },

  // ── SHOULDERS ─────────────────────────────────────────────────────────────
  {
    name: "Overhead Press",
    primaryMuscle: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.TRAPS, MuscleGroup.CORE],
    equipment: Equipment.BARBELL,
    movementPattern: MovementPattern.VERTICAL_PUSH,
    difficulty: Difficulty.INTERMEDIATE,
    isCompound: true,
    exerciseFamily: "shoulder_press",
    isCustom: false,
  },
  {
    name: "Dumbbell Shoulder Press",
    primaryMuscle: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.TRAPS],
    equipment: Equipment.DUMBBELL,
    movementPattern: MovementPattern.VERTICAL_PUSH,
    difficulty: Difficulty.BEGINNER,
    isCompound: true,
    exerciseFamily: "shoulder_press",
    isCustom: false,
  },
  {
    name: "Plate-Loaded Shoulder Press",
    primaryMuscle: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.TRAPS],
    equipment: Equipment.MACHINE,
    movementPattern: MovementPattern.VERTICAL_PUSH,
    difficulty: Difficulty.BEGINNER,
    isCompound: true,
    exerciseFamily: "shoulder_press",
    isCustom: false,
  },
  {
    name: "Arnold Press",
    primaryMuscle: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.TRAPS],
    equipment: Equipment.DUMBBELL,
    movementPattern: MovementPattern.VERTICAL_PUSH,
    difficulty: Difficulty.INTERMEDIATE,
    isCompound: true,
    exerciseFamily: "shoulder_press",
    isCustom: false,
  },
  {
    name: "Lateral Raise",
    primaryMuscle: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.TRAPS],
    equipment: Equipment.DUMBBELL,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "lateral_raise",
    isCustom: false,
  },
  {
    name: "Cable Lateral Raise",
    primaryMuscle: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.TRAPS],
    equipment: Equipment.CABLE,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "lateral_raise",
    isCustom: false,
  },
  {
    name: "Rear Delt Fly",
    primaryMuscle: MuscleGroup.SHOULDERS,
    secondaryMuscles: [MuscleGroup.TRAPS, MuscleGroup.BACK],
    equipment: Equipment.DUMBBELL,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "lateral_raise",
    isCustom: false,
  },

  // ── LEGS ──────────────────────────────────────────────────────────────────
  {
    name: "Back Squat",
    primaryMuscle: MuscleGroup.QUADS,
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.CORE],
    equipment: Equipment.BARBELL,
    movementPattern: MovementPattern.SQUAT,
    difficulty: Difficulty.ADVANCED,
    isCompound: true,
    exerciseFamily: "squat",
    isCustom: false,
  },
  {
    name: "Front Squat",
    primaryMuscle: MuscleGroup.QUADS,
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.CORE],
    equipment: Equipment.BARBELL,
    movementPattern: MovementPattern.SQUAT,
    difficulty: Difficulty.ADVANCED,
    isCompound: true,
    exerciseFamily: "squat",
    isCustom: false,
  },
  {
    name: "Bulgarian Split Squat",
    primaryMuscle: MuscleGroup.QUADS,
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS, MuscleGroup.CORE],
    equipment: Equipment.DUMBBELL,
    movementPattern: MovementPattern.SQUAT,
    difficulty: Difficulty.INTERMEDIATE,
    isCompound: true,
    exerciseFamily: "squat",
    isCustom: false,
  },
  {
    name: "Machine Leg Press",
    primaryMuscle: MuscleGroup.QUADS,
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
    equipment: Equipment.MACHINE,
    movementPattern: MovementPattern.SQUAT,
    difficulty: Difficulty.BEGINNER,
    isCompound: true,
    exerciseFamily: "leg_press",
    isCustom: false,
  },
  {
    name: "Sled Leg Press",
    primaryMuscle: MuscleGroup.QUADS,
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
    equipment: Equipment.MACHINE,
    movementPattern: MovementPattern.SQUAT,
    difficulty: Difficulty.BEGINNER,
    isCompound: true,
    exerciseFamily: "leg_press",
    isCustom: false,
  },
  {
    name: "Hack Squat",
    primaryMuscle: MuscleGroup.QUADS,
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
    equipment: Equipment.MACHINE,
    movementPattern: MovementPattern.SQUAT,
    difficulty: Difficulty.BEGINNER,
    isCompound: true,
    exerciseFamily: "squat",
    isCustom: false,
  },
  {
    name: "Leg Extension",
    primaryMuscle: MuscleGroup.QUADS,
    secondaryMuscles: [],
    equipment: Equipment.MACHINE,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "leg_extension",
    isCustom: false,
  },
  {
    name: "Romanian Deadlift",
    primaryMuscle: MuscleGroup.HAMSTRINGS,
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.BACK],
    equipment: Equipment.BARBELL,
    movementPattern: MovementPattern.HINGE,
    difficulty: Difficulty.INTERMEDIATE,
    isCompound: true,
    exerciseFamily: "hip_hinge",
    isCustom: false,
  },
  {
    name: "Leg Curl",
    primaryMuscle: MuscleGroup.HAMSTRINGS,
    secondaryMuscles: [MuscleGroup.GLUTES],
    equipment: Equipment.MACHINE,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "leg_curl",
    isCustom: false,
  },
  {
    name: "Seated Leg Curl",
    primaryMuscle: MuscleGroup.HAMSTRINGS,
    secondaryMuscles: [],
    equipment: Equipment.MACHINE,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "leg_curl",
    isCustom: false,
  },
  {
    name: "Hip Thrust",
    primaryMuscle: MuscleGroup.GLUTES,
    secondaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.CORE],
    equipment: Equipment.BARBELL,
    movementPattern: MovementPattern.HINGE,
    difficulty: Difficulty.INTERMEDIATE,
    isCompound: true,
    exerciseFamily: "hip_hinge",
    isCustom: false,
  },
  {
    name: "Hip Abduction Machine",
    primaryMuscle: MuscleGroup.GLUTES,
    secondaryMuscles: [],
    equipment: Equipment.MACHINE,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "hip_abduction",
    isCustom: false,
  },
  {
    name: "Hip Adduction Machine",
    primaryMuscle: MuscleGroup.QUADS,
    secondaryMuscles: [MuscleGroup.GLUTES],
    equipment: Equipment.MACHINE,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "hip_adduction",
    isCustom: false,
  },
  {
    name: "Calf Raise",
    primaryMuscle: MuscleGroup.CALVES,
    secondaryMuscles: [],
    equipment: Equipment.MACHINE,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "calf_raise",
    isCustom: false,
  },
  {
    name: "Standing Calf Raise",
    primaryMuscle: MuscleGroup.CALVES,
    secondaryMuscles: [],
    equipment: Equipment.BARBELL,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "calf_raise",
    isCustom: false,
  },

  // ── BICEPS ────────────────────────────────────────────────────────────────
  {
    name: "Barbell Curl",
    primaryMuscle: MuscleGroup.BICEPS,
    secondaryMuscles: [MuscleGroup.FOREARMS],
    equipment: Equipment.BARBELL,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "bicep_curl",
    isCustom: false,
  },
  {
    name: "EZ Bar Curl",
    primaryMuscle: MuscleGroup.BICEPS,
    secondaryMuscles: [MuscleGroup.FOREARMS],
    equipment: Equipment.EZ_BAR,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "bicep_curl",
    isCustom: false,
  },
  {
    name: "Dumbbell Curl",
    primaryMuscle: MuscleGroup.BICEPS,
    secondaryMuscles: [MuscleGroup.FOREARMS],
    equipment: Equipment.DUMBBELL,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "bicep_curl",
    isCustom: false,
  },
  {
    name: "Hammer Curl",
    primaryMuscle: MuscleGroup.BICEPS,
    secondaryMuscles: [MuscleGroup.FOREARMS],
    equipment: Equipment.DUMBBELL,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "bicep_curl",
    isCustom: false,
  },
  {
    name: "Concentration Curl",
    primaryMuscle: MuscleGroup.BICEPS,
    secondaryMuscles: [],
    equipment: Equipment.DUMBBELL,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "bicep_curl",
    isCustom: false,
  },
  {
    name: "Cable Curl",
    primaryMuscle: MuscleGroup.BICEPS,
    secondaryMuscles: [MuscleGroup.FOREARMS],
    equipment: Equipment.CABLE,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "bicep_curl",
    isCustom: false,
  },
  {
    name: "Incline Dumbbell Curl",
    primaryMuscle: MuscleGroup.BICEPS,
    secondaryMuscles: [MuscleGroup.FOREARMS],
    equipment: Equipment.DUMBBELL,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "bicep_curl",
    isCustom: false,
  },
  {
    name: "Preacher Dumbbell Curl",
    primaryMuscle: MuscleGroup.BICEPS,
    secondaryMuscles: [MuscleGroup.FOREARMS],
    equipment: Equipment.DUMBBELL,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "bicep_curl",
    isCustom: false,
  },
  {
    name: "Preacher Barbell Curl",
    primaryMuscle: MuscleGroup.BICEPS,
    secondaryMuscles: [MuscleGroup.FOREARMS],
    equipment: Equipment.BARBELL,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "bicep_curl",
    isCustom: false,
  },

  // ── TRICEPS ───────────────────────────────────────────────────────────────
  {
    name: "Tricep Pushdown",
    primaryMuscle: MuscleGroup.TRICEPS,
    secondaryMuscles: [],
    equipment: Equipment.CABLE,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "tricep_extension",
    isCustom: false,
  },
  {
    name: "Overhead Tricep Extension",
    primaryMuscle: MuscleGroup.TRICEPS,
    secondaryMuscles: [],
    equipment: Equipment.DUMBBELL,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "tricep_extension",
    isCustom: false,
  },
  {
    name: "Skullcrusher",
    primaryMuscle: MuscleGroup.TRICEPS,
    secondaryMuscles: [],
    equipment: Equipment.BARBELL,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.INTERMEDIATE,
    isCompound: false,
    exerciseFamily: "tricep_extension",
    isCustom: false,
  },
  {
    name: "Close Grip Bench Press",
    primaryMuscle: MuscleGroup.TRICEPS,
    secondaryMuscles: [MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
    equipment: Equipment.BARBELL,
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    difficulty: Difficulty.INTERMEDIATE,
    isCompound: true,
    exerciseFamily: "tricep_extension",
    isCustom: false,
  },
  {
    name: "Tricep Extension Machine",
    primaryMuscle: MuscleGroup.TRICEPS,
    secondaryMuscles: [],
    equipment: Equipment.MACHINE,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "tricep_extension",
    isCustom: false,
  },
  {
    name: "Cable Tricep Kickback",
    primaryMuscle: MuscleGroup.TRICEPS,
    secondaryMuscles: [],
    equipment: Equipment.CABLE,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "tricep_extension",
    isCustom: false,
  },

  // ── ADDITIONAL ────────────────────────────────────────────────────────────
  {
    name: "Seated Dip Machine",
    primaryMuscle: MuscleGroup.TRICEPS,
    secondaryMuscles: [MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
    equipment: Equipment.MACHINE,
    movementPattern: MovementPattern.VERTICAL_PUSH,
    difficulty: Difficulty.BEGINNER,
    isCompound: true,
    exerciseFamily: "dip",
    isCustom: false,
  },
  {
    name: "Dumbbell Fly",
    primaryMuscle: MuscleGroup.CHEST,
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    equipment: Equipment.DUMBBELL,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "fly",
    isCustom: false,
  },
  {
    name: "Single Arm Tricep Cable Pushdown",
    primaryMuscle: MuscleGroup.TRICEPS,
    secondaryMuscles: [],
    equipment: Equipment.CABLE,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "tricep_extension",
    isCustom: false,
  },
  {
    name: "Chest-Supported T-Bar Row",
    primaryMuscle: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.LATS, MuscleGroup.BICEPS, MuscleGroup.TRAPS],
    equipment: Equipment.MACHINE,
    movementPattern: MovementPattern.HORIZONTAL_PULL,
    difficulty: Difficulty.BEGINNER,
    isCompound: true,
    exerciseFamily: "row",
    isCustom: false,
  },
  {
    name: "Back Extension Machine",
    primaryMuscle: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
    equipment: Equipment.MACHINE,
    movementPattern: MovementPattern.HINGE,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "hip_hinge",
    isCustom: false,
  },
  {
    name: "Arm Curl Machine",
    primaryMuscle: MuscleGroup.BICEPS,
    secondaryMuscles: [MuscleGroup.FOREARMS],
    equipment: Equipment.MACHINE,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "bicep_curl",
    isCustom: false,
  },
  {
    name: "Diverging Seated Row",
    primaryMuscle: MuscleGroup.BACK,
    secondaryMuscles: [MuscleGroup.LATS, MuscleGroup.BICEPS, MuscleGroup.TRAPS],
    equipment: Equipment.MACHINE,
    movementPattern: MovementPattern.HORIZONTAL_PULL,
    difficulty: Difficulty.BEGINNER,
    isCompound: true,
    exerciseFamily: "row",
    isCustom: false,
  },

  // ── CORE ──────────────────────────────────────────────────────────────────
  {
    name: "Plank",
    primaryMuscle: MuscleGroup.CORE,
    secondaryMuscles: [MuscleGroup.SHOULDERS, MuscleGroup.GLUTES],
    equipment: Equipment.BODYWEIGHT,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "core",
    isCustom: false,
  },
  {
    name: "Hanging Leg Raise",
    primaryMuscle: MuscleGroup.ABS,
    secondaryMuscles: [MuscleGroup.CORE, MuscleGroup.LATS],
    equipment: Equipment.BODYWEIGHT,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.INTERMEDIATE,
    isCompound: false,
    exerciseFamily: "core",
    isCustom: false,
  },
  {
    name: "Cable Crunch",
    primaryMuscle: MuscleGroup.ABS,
    secondaryMuscles: [MuscleGroup.CORE],
    equipment: Equipment.CABLE,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.BEGINNER,
    isCompound: false,
    exerciseFamily: "core",
    isCustom: false,
  },
  {
    name: "Ab Wheel Rollout",
    primaryMuscle: MuscleGroup.CORE,
    secondaryMuscles: [MuscleGroup.ABS, MuscleGroup.SHOULDERS, MuscleGroup.LATS],
    equipment: Equipment.BODYWEIGHT,
    movementPattern: MovementPattern.ISOLATION,
    difficulty: Difficulty.ADVANCED,
    isCompound: false,
    exerciseFamily: "core",
    isCustom: false,
  },
  {
    name: "Cable Woodchopper",
    primaryMuscle: MuscleGroup.CORE,
    secondaryMuscles: [MuscleGroup.ABS, MuscleGroup.SHOULDERS],
    equipment: Equipment.CABLE,
    movementPattern: MovementPattern.ROTATION,
    difficulty: Difficulty.INTERMEDIATE,
    isCompound: false,
    exerciseFamily: "core",
    isCustom: false,
  },
];

async function main() {
  for (const ex of exercises) {
    await prisma.exercise.upsert({
      where: { name: ex.name },
      update: {
        primaryMuscle: ex.primaryMuscle,
        secondaryMuscles: ex.secondaryMuscles,
        equipment: ex.equipment,
        movementPattern: ex.movementPattern,
        difficulty: ex.difficulty,
        isCompound: ex.isCompound,
        exerciseFamily: ex.exerciseFamily,
      },
      create: ex,
    });
  }
  console.log(`Seeded ${exercises.length} exercises.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
